WITH CTE AS(
SELECT
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTED_AT)),
CASE WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat', 'Sun')
THEN 'Weenkend'
ELSE 'Business day'
END AS Day_type,
CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2) THEN 'Winter'
     WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5) THEN 'Spring'
     WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8) THEN 'Summer'
     ELSE 'Autumn'
END AS Season_of_the_year


from {{ source('demo', 'bike') }}
)
SELECT * FROM CTE